config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  namespace :my do
    resources :papers,  only: [:new, :create, :index, :show, :edit, :update]
    resource  :profile, only: [:show, :edit, :update]
  end

  namespace :cleaners do
    resources :papers, only: [:index, :edit, :update]
  end

  namespace :board do
    resources :papers, only: [:index] do
      resources :reviews, only: [:new, :create]
    end
  end

  namespace :organizers do
    resources :papers, only: [:index, :show]
  end

  scope :auth do
    resource :github, only: :none do
      get    :callback, to: "sessions#create"
      get    :new,                              as: "sign_in"
      delete :destroy,  to: "sessions#destroy", as: "sign_out"
    end
  end
end

app/controllers/my/papers_controller.rb
# frozen_string_literal: true

class My::PapersController < ApplicationController
  layout "cfp"

  before_action :authenticate!
  before_action :authorize_speaker!
  before_action :check_closing_time!, only: [:new, :create, :edit, :update]

  # GET /papers
  def index
    @papers = current_user.papers.all
  end

  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # POST /papers/create
  def create
    @paper = current_user.papers.build(paper_params)

    if @paper.save
      redirect_to my_paper_path(@paper)
    else
      flash[:error] = @paper.errors.full_messages.to_sentence.capitalize
      render :new
    end
  end

  # GET /papers/:id
  def show
    @paper = find_paper
  end

  # GET /papers/:id/edit
  def edit
    @paper = find_paper
  end

  # PATCH /papers/:id
  def update
    @paper = find_paper

    if @paper.update(paper_params)
      redirect_to my_paper_path(@paper)
    else
      flash[:error] = @paper.errors.full_messages.to_sentence.capitalize
      render :edit
    end
  end

  private

  def paper_params
    params.require(:paper).permit(:speaker_slot, :title, :abstract, :outline).merge(status: paper_status)
  end

  def paper_status
    if params[:draft]
      :draft
    elsif params[:withdraw]
      :withdrawn
    else
      :submitted
    end
  end

  def find_paper
    current_user.papers.find(params[:id])
  end

  def check_closing_time!
    return if current_conference.cfp_open?

    redirect_to my_papers_path, flash: { notice: "The CFP for this year's RDRC has closed" }
  end
end

app/controllers/my/profiles_controller.rb
# frozen_string_literal: true

class My::ProfilesController < ApplicationController
  layout "cfp"

  before_action :authenticate!
  before_action :authorize_speaker!

  # GET /profile
  def show
    @user = current_user
  end

  # GET /profile/edit
  def edit
    @user = current_user
  end

  # PATCh /profile
  def update
    @user = current_user

    if @user.update(user_params)
      redirect_to my_profile_path
    else
      flash[:error] = @user.errors.full_messages.to_sentence.capitalize
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:bio)
  end
end

app/views/my/profiles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">

      <h1>Edit profile</h1>
      <span><%= @user.email %></h1>

      <%= form_for @user, url: my_profile_path, method: :patch do |f| %>

        <div class="form-group">
          <%= f.label :bio %>
          <%= f.text_area :bio, class: "form-control" %>
        </div>

        <div class="form-controls text-right">
          <%= f.submit "Save changes", class: "btn btn-primary" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/my/profiles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">

      <h1><%= @user.name %></h1>
      <span><%= @user.email %></h1>

      <%= image_tag @user.avatar_url if @user.avatar_url %>

      <p><%= @user.bio %></p>

      <div class="text-right">
        <%= link_to "Edit", edit_my_profile_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>