config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  namespace :my do
    resources :papers,  only: [:new, :create, :index, :show, :edit, :update]
    resource  :profile, only: [:show, :edit, :update]
  end

  namespace :cleaners do
    resources :papers, only: [:index, :edit, :update]
  end

  namespace :board do
    resources :papers, only: [:index] do
      resources :reviews, only: [:new, :create]
    end
  end

  namespace :organizers do
    resources :papers, only: [:index, :show]
  end

  scope :auth do
    resource :github, only: :none do
      get    :callback, to: "sessions#create"
      get    :new,                              as: "sign_in"
      delete :destroy,  to: "sessions#destroy", as: "sign_out"
    end
  end
end

app/models/paper.rb
# frozen_string_literal: true

class Paper < ApplicationRecord
  default_scope -> { order(created_at: :desc) }

  belongs_to :user, inverse_of: :papers

  has_many :reviews, inverse_of: :paper

  with_options unless: :draft? do
    validates :abstract, presence: true
    validates :outline,  presence: true
  end
  with_options if: :scrubbed? do
    validates :scrubbed_outline, presence: true
  end
  validates :title,        presence: true
  validates :status,       presence: true
  validates :speaker_slot, presence: true

  enum status:       [:draft, :submitted, :scrubbed, :accepted, :rejected, :withdrawn].freeze
  enum speaker_slot: [:lightning, :regular].freeze

  def editable?
    draft? || submitted?
  end

  def review_by(user)
    reviews.find_by(user: user) || NoReview.new
  end

  def review_score
    return 0 if reviews.none?

    (reviews.sum(:score).to_f / reviews.count).round(2)
  end

  def review_score_diff
    return 0 if reviews.none?

    (review_score.to_f - reviews.minimum(:score)).round(2)
  end
end

app/controllers/board/papers_controller.rb
# frozen_string_literal: true

class Board::PapersController < ApplicationController
  layout "cfp"

  before_action :authenticate!
  before_action :authorize_reviewer!

  # GET board/papers
  def index
    @papers = PapersForReviewFinder.new(current_user)
  end

  private

  def find_paper
    Paper.find(params[:id])
  end

  def find_review
    find_paper.reviews.find_or_initialize_by(user: current_user)
  end
end

app/controllers/cleaners/papers_controller.rb
# frozen_string_literal: true

class Cleaners::PapersController < ApplicationController
  layout "cfp"

  before_action :authenticate!
  before_action :authorize_cleaner!

  # GET cleaners/papers
  def index
    @papers = Paper.where(status: [:submitted, :scrubbed])
  end

  # GET cleaners/papers/:id/edit
  def edit
    @paper = find_paper
  end

  # PATCH cleaners/papers/:id
  def update
    @paper = find_paper

    if @paper.update(paper_params)
      redirect_to cleaners_papers_path
    else
      flash[:error] = @paper.errors.full_messages.to_sentence.capitalize
      render :edit
    end
  end

  private

  def paper_params
    params.require(:paper).permit(:scrubbed_outline).merge(status: :scrubbed)
  end

  def find_paper
    Paper.find(params[:id])
  end
end

app/controllers/my/papers_controller.rb
# frozen_string_literal: true

class My::PapersController < ApplicationController
  layout "cfp"

  before_action :authenticate!
  before_action :authorize_speaker!
  before_action :check_closing_time!, only: [:new, :create, :edit, :update]

  # GET /papers
  def index
    @papers = current_user.papers.all
  end

  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # POST /papers/create
  def create
    @paper = current_user.papers.build(paper_params)

    if @paper.save
      redirect_to my_paper_path(@paper)
    else
      flash[:error] = @paper.errors.full_messages.to_sentence.capitalize
      render :new
    end
  end

  # GET /papers/:id
  def show
    @paper = find_paper
  end

  # GET /papers/:id/edit
  def edit
    @paper = find_paper
  end

  # PATCH /papers/:id
  def update
    @paper = find_paper

    if @paper.update(paper_params)
      redirect_to my_paper_path(@paper)
    else
      flash[:error] = @paper.errors.full_messages.to_sentence.capitalize
      render :edit
    end
  end

  private

  def paper_params
    params.require(:paper).permit(:speaker_slot, :title, :abstract, :outline).merge(status: paper_status)
  end

  def paper_status
    if params[:draft]
      :draft
    elsif params[:withdraw]
      :withdrawn
    else
      :submitted
    end
  end

  def find_paper
    current_user.papers.find(params[:id])
  end

  def check_closing_time!
    return if current_conference.cfp_open?

    redirect_to my_papers_path, flash: { notice: "The CFP for this year's RDRC has closed" }
  end
end

app/controllers/organizers/papers_controller.rb
# frozen_string_literal: true

class Organizers::PapersController < ApplicationController
  layout "cfp"

  before_action :authenticate!
  before_action :authorize_organizer!

  # GET organizers/papers
  def index
    @papers = Paper.scrubbed.includes(:reviews).sort_by { |p| -p.review_score }
  end

  # GET organizers/paper/:id
  def show
    @paper = find_paper
  end

  private

  def find_paper
    Paper.find(params[:id])
  end
end

app/controllers/papers_controller.rb
# frozen_string_literal: true

class PapersController < ApplicationController
  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # POST /papers/create
  def create
    @paper = Paper.new(paper_params)

    if @paper.save
      redirect_to paper_path(@paper)
    else
      flash[:error] = @paper.errors.full_messages.to_sentence.capitalize
      render :new
    end
  end

  # GET /papers/:id
  def show
    @paper = find_paper
  end

  private

  def paper_params
    params.require(:paper).permit(:title, :abstract)
  end

  def find_paper
    Paper.find(params[:id])
  end
end

app/views/organizers/papers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>Reviewed</h1>

      <table class="table table-striped">
        <thead>
        <tr>
          <th>Title</th>
          <th>Speaker</th>
          <th class="text-center">Review Score</th>
          <th></th>
        </tr>
        </thead>

        <tbody>

        <% @papers.each do |paper| %>

            <tr>
              <td>
                <%= paper.title %>
                <span class="label label-primary"><%= paper.speaker_slot %></span>
              </td>
              <td><%= paper.user.name %></td>
              <td class="text-center"><%= number_with_precision paper.review_score, precision: 2 %></td>
              <td class="text-right"><%= link_to "Show", organizers_paper_path(paper), class: "btn btn-default" %></td>
            </tr>

        <% end %>

        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/organizers/papers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8">

      <h1><%= @paper.title %></h1>
      <p>By: <%= @paper.user.name %></p>
      <span class="label label-primary"><%= @paper.speaker_slot %></span>

      <h2>Abstract</h2>
      <p><%= simple_format @paper.abstract %></p>

      <h2>Outline</h2>
      <p><%= simple_format @paper.outline %></p>

    </div>

    <div class="col-xs-12 col-sm-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Review score</h3>
        </div>
        <div class="panel-body text-center">
          <%= number_with_precision @paper.review_score, precision: 2 %> (±<%= number_with_precision @paper.review_score_diff, precision: 2 %>)
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Review comments</h3>
        </div>
        <div class="panel-body">
          <% @paper.reviews.each do |review| %>
            <%= review.comments %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>