config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  namespace :my do
    resources :papers,  only: [:new, :create, :index, :show, :edit, :update]
    resource  :profile, only: [:show, :edit, :update]
  end

  namespace :cleaners do
    resources :papers, only: [:index, :edit, :update]
  end

  namespace :board do
    resources :papers, only: [:index] do
      resources :reviews, only: [:new, :create]
    end
  end

  namespace :organizers do
    resources :papers, only: [:index, :show]
  end

  scope :auth do
    resource :github, only: :none do
      get    :callback, to: "sessions#create"
      get    :new,                              as: "sign_in"
      delete :destroy,  to: "sessions#destroy", as: "sign_out"
    end
  end
end

app/views/layouts/_board_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "RDRC'17 CFP", board_papers_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <div class="navbar-form">
            <div class="form-group">
              <%= link_to "Review papers", board_papers_path, class: "btn btn-success" %>
            </div>
          </div>
        </li>
        <li><%= link_to "Sign out", sign_out_github_path, method: :delete %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_cleaner_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "RDRC'17 CFP", cleaners_papers_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <div class="navbar-form">
            <div class="form-group">
              <%= link_to "Scrub papers", cleaners_papers_path, class: "btn btn-success" %>
            </div>
          </div>
        </li>
        <li><%= link_to "Sign out", sign_out_github_path, method: :delete %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "RDRC'17 CFP", my_papers_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li>
            <div class="navbar-form">
              <div class="form-group">
                <%= link_to "New paper", new_my_paper_path, class: "btn btn-success" %>
              </div>
            </div>
          </li>
          <li><%= link_to "My papers", my_papers_path %></li>
          <li><%= link_to "My profile", my_profile_path %></li>
          <li><%= link_to "Sign out", sign_out_github_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", sign_in_github_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_organizer_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "RDRC'17 CFP", organizers_papers_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <div class="navbar-form">
            <div class="form-group">
              <%= link_to "Papers", organizers_papers_path, class: "btn btn-success" %>
            </div>
          </div>
        </li>
        <li><%= link_to "Sign out", sign_out_github_path, method: :delete %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_speaker_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "#{current_conference.name} CFP", my_papers_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li>
            <div class="navbar-form">
              <div class="form-group">
                <%= link_to "New paper", new_my_paper_path, class: "btn btn-success", disabled: current_conference.cfp_closed? %>
              </div>
            </div>
          </li>
          <li><%= link_to "My papers", my_papers_path %></li>
          <li><%= link_to "My profile", my_profile_path %></li>
          <li><%= link_to "Sign out", sign_out_github_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", sign_in_github_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RDRC'17 - Call For Papers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", "data-turbolinks-track": "reload", media: "all" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= flash_messages %>

    <%= yield %>
  </body>
</html>

app/views/layouts/cfp.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RDRC'17 - Call For Papers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", "data-turbolinks-track": "reload", media: "all" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" />

    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>

  <body>
    <% if current_user.cleaner? %>
      <%= render "layouts/cleaner_header" %>
    <% elsif current_user.reviewer? %>
      <%= render "layouts/board_header" %>
    <% elsif current_user.organizer? %>
      <%= render "layouts/organizer_header" %>
    <% else %>
      <%= render "layouts/speaker_header" %>
    <% end %>
    <%= flash_messages %>

    <%= yield %>
  </body>
</html>